### ISSUE TITLE
API error fetching repositories for an organization

### ISSUE THREAD

**Issue by jasonrudolph** [bswinnerton/launchbar-github#40] opened 2017-02-24 18:12 UTC
While testing out #39, I ran into the following issue (using version 46595877bb8e81a8a03d89cc7354db48903c1e67 of github.lbaction):

![demo](https://cloud.githubusercontent.com/assets/2988/23315129/d93c671c-fa92-11e6-9525-c654fda78d9e.gif)

**Comment by bswinnerton** [comment] 2017-02-24 18:35
I think you may be running into rate limits 😞 . The "Couldn't access the GitHub API" is a catchall error that I'd like to make more specific.

My hypothesis can be verified by going into the action editor and selecting "Enable Debug Log":

![screen shot 2017-02-24 at 1 30 06 pm](https://cloud.githubusercontent.com/assets/934497/23315715/64374560-fa95-11e6-8fef-d01a607019d6.png)

From there, if you restart LaunchBar and open the Console application and grep for "launchbar", you should be able to see the raw JSON responses coming back from the API.

I was able to reproduce this by trying to search for an organization which has a considerable amount of repositories.

One way to fix this would be to set a limit in the [`Account.repositories()`](https://github.com/bswinnerton/github.lbaction/blob/46595877bb8e81a8a03d89cc7354db48903c1e67/Contents/Scripts/account.js#L30-L84) logic. Right now it simply iterates over _all_ repositories, but this might diminish the usability 😔 .

**Comment by bswinnerton** [comment] 2017-02-24 18:46
> My hypothesis can be verified by going into the action editor and selecting "Enable Debug Log":

This process is a little easier now that https://github.com/bswinnerton/github.lbaction/pull/41 has been merged.

**Comment by bswinnerton** [comment] 2017-02-25 16:04
While this isn't showcased in the gif that you added in this post, I believe that the reason we're eating through the rate limit so quickly is due to the way that the suggestions script executes API calls.

Currently, when a user inputs text after say `atom/`, after every new character (`atom/a`, `atom/at`, etc), a new request is fired off before the first one can complete. This is not the case if you type `atom/` and then wait for the results to come back, because once they do, they've been cached.

I've written in to LaunchBar's support to see if there's any sort of mechanisms to "wait" until a user has finished typing and _then_ invoke the script. In the event there isn't such a mechanism, I've started a spike on "request locking" over in https://github.com/bswinnerton/github.lbaction/pull/42 that I think might help.

**Comment by bswinnerton** [comment] 2017-02-28 02:33
> I've written in to LaunchBar's support to see if there's any sort of mechanisms to "wait" until a user has finished typing and then invoke the script.

Unfortunately no such feature exists in LaunchBar. I think the best case forward would be:

1) Limiting the number of results that are returned by LaunchBar (https://github.com/bswinnerton/launchbar-github/pull/43) - which unfortunately means that you won't be able to search for all repositories
2) Wait for GitHub to bump their GraphQL API limits, which will likely happen after they come out of ["early access"](https://developer.github.com/early-access/graphql/).

**Comment by bswinnerton** [comment] 2017-04-27 19:32
> 2) Wait for GitHub to bump their GraphQL API limits, which will likely happen after they come out of ["early access"](https://developer.github.com/early-access/graphql/)

This has happened! I've bumped the limits to `100` (which should make 3x less requests) as of 3b1ce899a1599f1f36ea8d4f471354eae444045d. I'm going to close this out for now, but if you see it again please feel free to reopen this issue, @jasonrudolph.

**Closed by bswinnerton** 2017-04-27 19:32 UTC
